name: update

on:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make update
      - name: Run auto commit
        uses: stefanzweifel/git-auto-commit-action@v2.0.0
        with:
          commit_author_email: bob@archlinux.de
          commit_author_name: Maintenance Bob
          commit_message: Update WordPress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
