name: update

on:
  schedule:
    - cron: '0 1 */1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update WordPress and dependencies
        run: make update
      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update WordPress
          commit_user_name: Maintenance Bob
          commit_user_email: bob@archlinux.de
          commit_author: Maintenance Bob <bob@archlinux.de>
